package com.example.fasse_back.foodcomposition.model;

import lombok.Data;

@Data
public class FoodComposition {
    private String foodGroup;
    private String foodNo;
    private String searchNo;
    private String foodNm;
    private int refuse;
    private int enerc;
    private int enercKcal;
    private double water;
    private double protcaa;
    private double prot;
    private double fatnlea;
    private int chole;
    private double fat;
    private double choavlm;
    private String choavlmAdd;
    private double choavl;
    private double choavldf;
    private String choavldfAdd;
    private double fib;
    private int polyl;
    private double chocdf;
    private int oa;
    private double ash;
    private int na;
    private int k;
    private int ca;
    private int mg;
    private int p;
    private double fe;
    private double zn;
    private double cu;
    private double mn;
    private String blank;
    private int id;
    private int se;
    private int cr;
    private int mo;
    private int retol;
    private int carta;
    private int cartb;
    private int crypxb;
    private int cartbeq;
    private int vitaRae;
    private double vitd;
    private double tocpha;
    private double tocphb;
    private double tocphg;
    private double tocphd;
    private double vitk;
    private double thia;
    private double ribf;
    private double nia;
    private double ne;
    private double vitb6a;
    private double vitb12;
    private int fol;
    private double pantac;
    private double biot;
    private int vitc;
    private double alc;
    private double naclEq;
    private String memo;
}
