create table m_user
(
    id int auto_increment,
    user_name char(100) not null,
    constraint user_pk primary key (id)
);

create table m_food_composition
(
    food_group char(2) not null,
    food_no char(5) not null,
    search_no char(6) not null,
    food_nm varchar(200) not null,
    refuse int,
    enerc int,
    enerc_kcal int,
    water decimal(6,2),
    protcaa decimal(6,2),
    prot decimal(6,2),
    fatnlea decimal(6,2),
    chole int,
    fat decimal(6,2),
    choavlm decimal(6,2),
    choavlm_add char(1),
    choavl decimal(6,2),
    choavldf decimal(6,2),
    choavldf_add char(1),
    fib decimal(6,2),
    polyl int,
    chocdf decimal(6,2),
    oa int,
    ash decimal(6,2),
    na int,
    k int,
    ca int,
    mg int,
    p int,
    fe decimal(6,2),
    zn decimal(6,2),
    cu decimal(6,2),
    mn decimal(6,2),
    blank char(1),
    id int,
    se int,
    cr int,
    mo int,
    retol int,
    carta int,
    cartb int,
    crypxb int,
    cartbeq int,
    vita_rae int,
    vitd decimal(6,2),
    tocpha decimal(6,2),
    tocphb decimal(6,2),
    tocphg decimal(6,2),
    tocphd decimal(6,2),
    vitk decimal(6,2),
    thia decimal(6,2),
    ribf decimal(6,2),
    nia decimal(6,2),
    ne decimal(6,2),
    vitb6a decimal(6,2),
    vitb12 decimal(6,2),
    fol int,
    pantac decimal(6,2),
    biot decimal(6,2),
    vitc int,
    alc decimal(6,2),
    nacl_eq decimal(6,2),
    memo varchar(400),
    constraint user_pk primary key (food_group, food_no, search_no)
);
